name: Regent-FFT Tests
run-name: ${{ github.actor }} is testing Regent-FFT
on: [push]
jobs:
  regent-FFT-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: source env.sh
      - run: ./test.sh
