name: Regent-FFT Tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  regent-FFT-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ../legion/language/regent.py test/fft_test.rg 
