name: Regent-FFT Tests
run-name: ${{ github.actor }} is testing Regent-FFT
on: 
  push:
  workflow_dispatch:

jobs:
  regent-FFT-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04'] # 'macos-11' # FIXME: macOS is broken: https://github.com/StanfordLegion/legion/issues/213
        debug: ['1', '0']

    steps:
    - uses: Jimver/cuda-toolkit@v0.2.14
      id: cuda-toolkit
      with:
        cuda: '12.3.2'
    - run: nvcc -V