name: Regent-FFT Tests
run-name: ${{ github.actor }} is testing Regent-FFT
on: 
  push:
  workflow_dispatch:
jobs:
  regent-FFT-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04'] # 'macos-11' # FIXME: macOS is broken: https://github.com/StanfordLegion/legion/issues/213
        debug: ['1', '0']
    steps:
      - uses: actions/checkout@v1
      - run: git clone https://github.com/StanfordLegion/legion.git
      - run: DEBUG=1 USE_GASNET=0 legion/language/scripts/setup_env.py
      - run: source env.sh
      - run: ./install.py
      - run: ./legion/language/regent.py test/fft_test.rg
        env:
            DEBUG: ${{ matrix.debug }}
            USE_REGENT: '1'
            INSTALL_DEPS: '1'
            SUDO_COMMAND: sudo
