name: Regent-FFT Tests
run-name: ${{ github.actor }} is testing Regent-FFT
on: 
  push:
  workflow_dispatch:

jobs:
  regent-FFT-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04'] # 'macos-11' # FIXME: macOS is broken: https://github.com/StanfordLegion/legion/issues/213
        debug: ['1', '0']

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install CUDA Toolkit 11.6
      uses: nvidia/setup-cuda@v1
      with:
        cuda: '11.6'

    - name: Run test
      uses: actions/checkout@v1
      run: ./test.sh
      env:
        DEBUG: ${{ matrix.debug }}
        USE_REGENT: '1'
        INSTALL_DEPS: '1'
        SUDO_COMMAND: sudo
